# Generated by Django 5.0 on 2023-12-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='caution',
            field=models.TextField(blank=True),
        ),
    ]
