# Generated by Django 5.0 on 2023-12-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_datamodel_caution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='english_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='hindi_name',
            field=models.TextField(blank=True),
        ),
    ]
