# Generated by Django 5.0 on 2023-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_datamodel_english_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
