# Generated by Django 5.0 on 2023-12-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_medicine', models.CharField(max_length=200, unique=True)),
                ('Reference_name', models.CharField(max_length=10)),
                ('Dispensing_pack_size', models.CharField(max_length=10)),
                ('Main_indicator', models.TextField()),
                ('Dose', models.TextField()),
                ('Precaution', models.TextField(blank=True)),
                ('Preferred_use', models.CharField(blank=True, max_length=10)),
                ('Class', models.CharField(max_length=1)),
            ],
        ),
    ]
